# Generated by Django 4.1.4 on 2022-12-22 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memory',
            name='photo',
            field=models.ImageField(default='photos/default.png', upload_to='photos/%Y/%m/%d/'),
        ),
    ]
