# Generated by Django 4.1.4 on 2022-12-24 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_memory_latitude_memory_longitude'),
    ]

    operations = [
        migrations.RenameField(
            model_name='memory',
            old_name='Latitude',
            new_name='latitude',
        ),
        migrations.RenameField(
            model_name='memory',
            old_name='Longitude',
            new_name='longitude',
        ),
    ]
