# Generated by Django 4.1.4 on 2022-12-24 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_latitude_memory_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memory',
            name='slug',
            field=models.SlugField(max_length=255, verbose_name='Url'),
        ),
    ]
