name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.1
      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          cd app/
          pip install -r requirements.txt
      - name: Run tests
        run: |
          cd app/
          python manage.py test
               
            
